# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

ZSH_THEME="powerlevel10k/powerlevel10k"

# Vi-Mode
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='245'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='black'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='239'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='black'

if [ "$(uname)" = "Linux" ]; then
  POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'\uF17c' # tux
fi

# https://gist.github.com/cviebrock/985684a169cf9a2b117d99dd9415a448

# General
POWERLEVEL9K_MODE='nerdfont-complete'
#POWERLEVEL9K_COLOR_SCHEME='dark'

# Prompts
if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon ssh vi_mode context dir virtualenv vcs)
else
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator vi_mode dir virtualenv vcs)
fi
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history battery time)

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\ue0b0'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\ue0b2'
POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="╭"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰\uF460\uF460\uF460 "

# Dir segment
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=…
#POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{grey}\/%F{white}"
#POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
#POWERLEVEL9K_DIR_BACKGROUND="214"
#POWERLEVEL9K_DIR_BACKGROUND="#91d7e3"
#POWERLEVEL9K_DIR_BACKGROUND="#8aadf4"
POWERLEVEL9K_DIR_BACKGROUND="#a6da95"
POWERLEVEL9K_DIR_FOREGROUND="black"
#POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='241'
#POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'
#POWERLEVEL9K_DIR_HOME_BACKGROUND='241'
#POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
#POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='241'
#POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='white'

# Custom segment "now playing"
#POWERLEVEL9K_CUSTOM_NOW_PLAYING='~/.dotfiles/bin/nowplaying'
#POWERLEVEL9K_CUSTOM_NOW_PLAYING_BACKGROUND='blue'
#POWERLEVEL9K_CUSTOM_NOW_PLAYING_FOREGROUND='black'

# Root segment
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND='red'
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND='black'
POWERLEVEL9K_ROOT_ICON="\uf21b"

# Status segment
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
POWERLEVEL9K_STATUS_OK_BACKGROUND='black'
POWERLEVEL9K_STATUS_OK_FOREGROUND='236'
POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_COLOR='010'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='black'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='236'
POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_COLOR='red'

# Background jobs segment
POWERLEVEL9K_BACKGROUND_JOBS_ICON="\uf423"

# Battery segment
POWERLEVEL9K_BATTERY_CHARGING='107'
POWERLEVEL9K_BATTERY_CHARGED='blue'
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='30'
POWERLEVEL9K_BATTERY_LOW_COLOR='red'

# VCS segment
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='239'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='010'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='239'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='239'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='red'

# SSH segment
POWERLEVEL9K_SSH_BACKGROUND='blue'
POWERLEVEL9K_SSH_FOREGROUND='white'

# Context segment
POWERLEVEL9K_CONTEXT_TEMPLATE="\uf109 %m"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='white'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='blue'
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='white'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='red'

source $ZSH/oh-my-zsh.sh
