ZSH_THEME="powerlevel9k/powerlevel9k"
#ZSH_THEME="agnoster"

DEFAULT_USER="dpecos"

#ENABLE_CORRECTION="true"

#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir rbenv vcs)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(ssh status root_indicator background_jobs history load battery time)
#POWERLEVEL9K_BATTERY_STAGES=($'\u2581 ' $'\u2582 ' $'\u2583 ' $'\u2584 ' $'\u2585 ' $'\u2586 ' $'\u2587 ' $'\u2588 ')

#POWERLEVEL9K_COLOR_SCHEME="light"
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"

fpath=(/usr/local/share/zsh-completions $fpath)
